version: '3.9'

services:
  db:
    env_file:
      - .env
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD : ${MYSQL_PASSWORD}
    ports:
      - "${PORT}:3306"
    volumes:
      - LearnLog:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    
volumes:
  LearnLog: